//@flow

export const ADD_CHAT_MESSAGE = 'ADD_CHAT_MESSAGE';
export const ADD_POTENTIAL_NEXT_USER_MESSAGE = 'ADD_POTENTIAL_NEXT_USER_MESSAGE';
export const ADD_CONVERSATION_ID = 'ADD_CONVERSATION_ID';
export const TOGGLE_VOICE_INTERACTIVE = 'TOGGLE_VOICE_INTERACTIVE';
export const TOGGLE_CAPTURING_AUDIO = 'TOGGLE_CAPTURING_AUDIO';
export const SET_MESSAGE_MOUNTED = 'SET_MESSAGE_MOUNTED';
